### PR TITLE
Dev monitoring statistics and time series

### PR DESCRIPTION
**Pull request by mdorier**
This PR adds the customizable monitoring system, including an implementation that produces two files for statistics and time series, respectively.

This PR is huge, making a lot of changes in the existing file and adding a margo-default-monitoring.c file that is almost as long as margo-core.c, so commenting on every bit of code might not be reasonable. There is a unit test that tests the injection of a custom monitoring structure as well as the production of statistics and time series files. What I would be most interested in is general comments as well as a check for memory leaks. We can discuss on slack regarding the content of the JSON files produced or the structure of the code.

### CODE REVIEW

**Comment by carns** [comment]
[test-suite.log.gz](https://github.com/mochi-hpc/mochi-margo/files/9965912/test-suite.log.gz)

I've attached the address sanitizer output from `make check` on my system (the monitoring test fails, but that's probably just because I've set up asan to abort on leaks rather than any direct test failure).

(we do still need to make a github action for this; I haven't had a chance to look at how to do it yet)

**Comment by mdorier** [comment]
Thanks, those turned out to be 3 leaks: for 2 of them I forgot to free the JSON tree in the unit test, and for the last I didn't know I had to clear out the secondary UThash when indexing by 2 separate keys. Should be good now.

By the way if you want to see what the monitoring system outputs, check the `test.<hostname>.<pid>.stats.json` and `test.<hostname>.<pid>.series.json` files in your build directory after running the margo-monitoring unit test.

**Comment by carns** [comment]
A few general suggestions for general documentation (mostly for end-users):
- update the doc/instrumentation.md (or fold it into README.md, whatever makes sense) to describe how to set `MARGO_ENABLE_MONITOR` and any optional `margo_init()` json settings that an end user might be interested in
- add a comment at the top of margo-monitoring.h to clarify that it is the API for someone who wishes to implement a custom monitor
- remove the old margo-gen-profile utility

**Comment by carns** [comment]
A few suggestions for the json stats output format (some of this will duplicate what we've discussed on slack already):
- rename "timestamp" to something verbose like "relative_timestamp_from_create" or whatever is appropriate for the context
- put nestings in "handler" for convenience
- rename "forward" and "respond" to "iforward" and "irespond" to make sure to avoid confusion about if their durations represent complete blocking call durations (that was my initial assumption)
- maybe also rename "wait" to "iforward_wait" and "irespond_wait" to clarify what they are assumed to pair with?  I'm less certain on this suggestion.
- rename "*id*" to "*rpc_id*" to clarify what ID it is and be symmetrical with "*provider_id*"

**Comment by carns** [comment]
The code and the overall strategy is great, I just skimmed that, though, and focused mostly on how an end-user might interpret the docs and  output format.

**Comment by mdorier** [comment]
Everything done! Except for your first comment: I didn't notice that there were documentations in the margo code. Maybe that should be removed since all the Mochi documentation is on readthedocs? (and I'll add a page about monitoring on readthedocs)

**Comment by carns** [comment]
one more quick fix in the json:

- [ ] rename `parent_id` to `parent_rpc_id`

Beyond that I'm happy with the stats json output now, thanks!

**Comment by carns** [comment]
> Everything done! Except for your first comment: I didn't notice that there were documentations in the margo code. Maybe that should be removed since all the Mochi documentation is on readthedocs? (and I'll add a page about monitoring on readthedocs)

Yeah, looking closer at what's in there, the in-repo docs are too much considering that someone can get better explanations on rtd.  Some of it is probably stale.  Maybe we should adopt a semi-standard convention on what to include in the README.md for Mochi components that have a readthedocs presence?  I would suggest:

- synopsis/overview (i.e., what does the component do)
- brief dependencies list
- brief default compilation instructions
- pointer to rememberthedocs page for more in depth usage and design information

If that sounds right, then I could help clean out the existing docs as a separate PR (making sure that anything worthwhile is moved to the rtd page).  That's mostly orthogonal to the monitoring changes.

**Comment by mdorier** [comment]
More seriously, I did the parent_id => parent_rpc_id modification, and removed instrumentation.md. I suggest we do the changes to the README in another PR after this one is merged, and I'll have a readthedocs page about the monitoring system ready in a few days.

**Comment by carns** [comment]
> More seriously, I did the parent_id => parent_rpc_id modification, and removed instrumentation.md. I suggest we do the changes to the README in another PR after this one is merged, and I'll have a readthedocs page about the monitoring system ready in a few days.

Ok!  That works for me.

**Comment by carns** [comment]
@mdorier in the newest format:
```
carns-x1-7g ~/w/s/m/m/build (dev-monitoring-statistics=)> grep from_forward test.carns-x1-7g.1466715.stats.json
            "relative_timestamp_from_forward_start":{
            "relative_timestamp_from_forward_end":{
            "relative_timestamp_from_forward_start":{
            "relative_timestamp_from_forward_start":{
            "relative_timestamp_from_forward_end":{
            "relative_timestamp_from_forward_start":{
```

... does "forward"  refer to the "iforward" or "forward_cb" event?  Might need to clarify (and do likewise for the "from_respond" ones too).

**Comment by mdorier** [comment]
Good point, will do.

**Pull request merged**
