### PR TITLE
remove superfluous ABT_thread_yield() call

### PR DESCRIPTION
**Pull request by carns**
improves ops/s by 2-3% in sequntial benchmarks

### CODE REVIEW

**Comment by mdorier** [comment]
Careful here; this `ABT_thread_yield` was added to solve this: https://github.com/mochi-hpc/mochi-margo/pull/278

**Comment by carns** [comment]
Ah, shoot.  I keep forgetting about the desire to support the use case where execution streams are mapped to multiple pools.

I'll take a closer look.  If that's the case (that we need to do a blind yield, even if there is nothing to do in the current pool, in case there is another pool to be serviced) then its the _other_ yield call at https://github.com/mochi-hpc/mochi-margo/blob/main/src/margo-core.c#L1984 that needs to be removed.

It doesn't make sense to do a yield and then a few lines further down in the function yield again, so one of them needs to go.  It sounds like we need to cut the one that has guards around it checking the current pool and go with the one that yields no matter what.

I haven't checked the Argobots code, but for some reason these yields have a measurable cost in low latency operations even if there is nothing to yield to.  I must be the cost of pushing the work unit back into the pool (possibly checking other pools depending on the ES configuration) and then popping it back out.

**Comment by carns** [comment]
Trying another strategy with this commit (and also more carefully commenting the reasoning for the logic).  If this passes CI then I think it will work.

**Comment by carns** [comment]
Yeah this variation seems to work fine.  Squashing and merging.  Thanks for pointing out the problem with the original attempt @mdorier

**Pull request merged**
