### PR TITLE
use loopback interface for tcp unit tests

### PR DESCRIPTION
**Pull request by carns**

### CODE REVIEW

**Comment by carns** [comment]
I'm not sure if this will work on non-linux systems (i.e. macos), but I'm also not sure how important this unit test is on non-linux systems.

**Comment by mdorier** [comment]
The problem with the forward test hanging was cause by your docker installation?
(as a side note, Mac doesn't support tcp, we need to use sockets on it, but I'm not using Mac to develop anyway)

**Comment by mdorier** [comment]
Otherwise it looks good. I wonder if we couldn't just use na+sm for all tests? I don't know why this one specifically uses tcp.

**Comment by carns** [comment]
Yes.  I installed docker on my laptop a few days ago, which added a docker0 interface (for communication among containers).  For some reason libfabric is selecting that interface to initially bind to, but then a subset of traffic ends up on a different interface as well (maybe due to arp redirection or something; I'm not sure).  At any rate, the presence of this docker0 interface seems to confuse libfabric ofi_tcp on the host machine.  This would have been fine on a guest container.

The docker0 network interface could probably be configured differently to avoid this, but I think it might be safer to just use the loopback interface for unit tests to generically avoid this potential class of problem.

**Comment by carns** [comment]
> Otherwise it looks good. I wonder if we couldn't just use na+sm for all tests? I don't know why this one specifically uses tcp.

Yeah actually that's a good question.  It seems like there was a reason but it's not documented in the unit test comments...

**Comment by carns** [comment]
> > Otherwise it looks good. I wonder if we couldn't just use na+sm for all tests? I don't know why this one specifically uses tcp.
> 
> Yeah actually that's a good question. It seems like there was a reason but it's not documented in the unit test comments...

In fact, we've made this observation before: https://github.com/mochi-hpc/mochi-margo/commit/5b08413d6be04b8cb874fa578a718d7fcab2708a

**Comment by carns** [comment]
Yeah, let me open another pull request to switch to na+sm for this test instead.  That seems like a more sensible solution since it's more likely to be available anyway and other unit tests already use that as the default transport.

**Pull request closed without merging**
