### PR TITLE
Add github workflow

### PR DESCRIPTION
**Pull request by KoyamaSohei**
## Desription

This PR add [GitHub Actions workflow](https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions) and run `make check` on CI environment.

This offers a variety of benefits, but especially we can check if changes will break existing behavior.

I'll be sending some patches in the future, but first we need to be careful not to break the existing behavior.

## License

I'm undergraduate at University of Tsukuba, and University of Tsukuba has signed a [license agreement](https://www.mcs.anl.gov/research/projects/mochi/contributing/).

### CODE REVIEW

**Comment by mdorier** [comment]
Thanks for the contribution! Just a note: we have just migrated the sds-repo repository from Argonne's xgitlab to github: https://github.com/mochi-hpc/mochi-spack-packages so you might want to update your code.

Also, `make check` in Margo doesn't do much; we don't have extensive tests set up. I guess at least if will make sure that it builds correctly.

**Comment by KoyamaSohei** [comment]
@mdorier 

Thank you for your quick reply!

>  we have just migrated the sds-repo repository from Argonne's xgitlab to github: https://github.com/mochi-hpc/mochi-spack-packages so you might want to update your code.

fixed that, thanks.

> Also, make check in Margo doesn't do much; we don't have extensive tests set up. 

Certainly there are few test cases right now.

For the time being I will work on [another issue](https://github.com/mochi-hpc/mochi-margo/issues/113).  

Please merge this when you feel you need it

**Comment by KoyamaSohei** [comment]
It doesn't have to be now, When you need it someday :)

**Comment by mdorier** [comment]
I'll probably take care of it after the SC deadline. I've been wanting to look at github workflows for a while now.

**Comment by carns** [comment]
Thanks @KoyamaSohei, this is a good idea.

**Pull request merged**
